### ISSUE TITLE
Zadanie: Re: Transcription

### ISSUE THREAD

**Issue by pbiecek** [BetaAndBit/BetaBitRgame#10]
Jedyny moment w którym się zaciąłem i na który zeszło mi najwięcej czasu to wywołanie funkcji frequon(subject = "Re: Transcription", content = "text_you_will_get"). Żądanym tekstem jest oryginalna zawartość obiektu roses ze znakami zastąpionymi tylko i wyłącznie na podstawie częstości występowania liter w języku angielskim jak i w samym tekście. Przystępując do tego zadania utwierdziłem się w przekonaniu, że jako content trzeba przesłać już całkowicie przerobiony tekst (z naniesionymi poprawkami, których dokonuję się dopiero w następnym zadaniu). Dopiero po jakimś czasie dotarło do mnie, że pospieszyłem się z rozwiązaniem.

**Comment by pbiecek** [comment]
czy coś z tym robić?

**Comment by katarzynaf** [comment]
Rzeczywiście, to może być mylące. Można w treści wiadomości podkreślić ten fakt.

You've Got Mail

From: 154eb7278fc44650bdd2bb39bb2b5c69@mail.tor
To: c81632dce28ca740f2f2503656f3d62a@mail.tor
Subject: Transcription

Great job! Now, when we do know which letters are used the most often and which are the least common, we can combine them with well-known English frequencies of letters.
We have prepared and attached the `EnglishLetterFrequency` dataset.
It contains frequencies of letters in the English language.

Now you can substitute old ciphered letters with the new English letters (proponuję dopisac:) **accordingly to their frequencies**.
Such operation is called character translation / transliteration.
Can you pass the transliterated message to us?

Send us reply: `frequon(subject = "Re: Transcription", content = "text_you_will_get")`.
We wish you luck!

Best regards!

Gdybym umiała dotrzeć do miejsca, które przechowuje wiadomości, mogłabym te cztery słowa dopisać.

**Comment by pbiecek** [comment]
Treści są w repozytorium BetaBitTools, te słowa dodam
