### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by tzoltak** [BetaAndBit/BetaBitRgame#11]
Trying to install package from GitHub I get an error:

install_github("BetaAndBit/BetaBitRgame")
(...)
Error in nchar(text) : invalid multibyte string, element 1

**Comment by pbiecek** [comment]
I will check problems with GitHub (it is probably something system specific, installation s working on OSX

But now, please try the CRAN version from

`
install.packages("BetaBit")
`

**Comment by pbiecek** [comment]
I've removed all non ASCII characters from DESCRIPTION,
should help
