### ISSUE TITLE
Niekonsekwencja w zagadce z odnalezieniem szyfru

### ISSUE THREAD

**Issue by zozlak** [BetaAndBit/BetaBitRgame#3]
Zaszyfrowana wiadomość nie zawiera dwóch liter: "k" i "u", w związku z czym do poprawnego odszyfrowania wiadomości nie trzeba znać (co więcej, analizując zaszyfrowaną wiadomość nie da się poznać) ich odszyfrowanych odpowiedników (wiadomo, że będą to "z" i "j", ale nie wiadomo, jak się sparują). W związku z tym `frequon( subject="Re: Key", content=c(old = "abcdef....z", new = "newlettersrespectively"))` powinien:
- albo akceptować wartości z dowolnymi mapowaniami "k" i "u" na "j" i "z" (a więc zarówno {k=>j, u=>z}, jak i {k=>z, u=>j})
- albo w wypadku podania mapowań "k" i "u" niedających poprawnego rozwiązania kolejnej zagadki (i poprawnych wszystkich pozostałych mapowań) zwracać komunikat błędu inny niż _Nice try. However, this key does not translate the message correctly._ (gdyż samą wiadomość odszyfrować da się poprawnie, a problem dotyczy jedynie kolejnej zagadki, w której potrzebne jest mapowanie dla "u")
- albo zaszyfrowany tekst należy uzupełnić, tak by występowały w nim w postaci zaszyfrowanej "k" oraz "u"

**Comment by pbiecek** [comment]
to chyba trzeba poprawić,, na razie to wygląda jak błąd

**Comment by pbiecek** [comment]
poprawione w 1.3.
btw, podobnie nie są sprawdzane litery x i v
