### ISSUE TITLE
transliteracja

### ISSUE THREAD

**Issue by pbiecek** [BetaAndBit/BetaBitRgame#4]
Cyprian:
1) mylne dla mnie okazało się poszukiwanie dalszych transliteracji po
zamianie według częstości liter - przez pewien czas nie wysyłałem
odpowiedzi z rozwiązaniem, bo nie byłem pewien, ale zastanawiałem się, co
by wyszło przy innej kolejności częstości zaobserwowanych liter (niektóre
były równoliczne) w stosunku do kolejności według ogólnych częstości,

**Comment by pbiecek** [comment]
czy to zmieniać?

**Comment by katarzynaf** [comment]
Jak dopiszemy to zdanie, które zasugerowałam w issue [Zadanie: Re: Transcription #10](https://github.com/BetaAndBit/BetaBitRgame/issues/10) myślę, że to powinno być już jasne.
