### ISSUE TITLE
zlozenie transliteracji

### ISSUE THREAD

**Issue by pbiecek** [BetaAndBit/BetaBitRgame#5]
Cyprian:
2) przy transliteracji liter według słów warto może podkreślić, że chodzi
o oryginalne w zakodowanej wiadomości, a nie te zamienione na poprzednim
etapie, de facto złożenie dwu transliteracji, chyba że pominięcie
poprzedniego etapu

**Comment by pbiecek** [comment]
KF, czy poprawisz to?

**Comment by katarzynaf** [comment]
Na tym etapie na koniec jest informacja:

Type:
`frequon( subject="Re: Key", content=c(old = "abcdef....z", new = "newlettersrespectively"))`**, where `old` are the letters in the code`s sense** and `new` are fitted real letters.

Żeby było to bardziej jednoznaczne, można napisać: _where `old` are the letters from the `roses` message_. Wydaje się, że tak będzie jaśniej.

**Comment by katarzynaf** [comment]
Nie mogę znaleźć miejsca, w którym przechowywane są te wiadomości, żeby podmienić to zdanie... Nieźle zaszyfrowany ten kod ;]

**Comment by pbiecek** [comment]
ok, zmieniłem ten zapis
