### ISSUE TITLE
+ jedno zadanie

### ISSUE THREAD

**Issue by pbiecek** [BetaAndBit/BetaBitRgame#9]
6) spodziewałem się też transliteracji tekstu w ostatnim zbiorze danych
jako zadania

**Comment by pbiecek** [comment]
czy coś z tym robić?

**Comment by katarzynaf** [comment]
Nie raczej, tym bardziej, że tam jest ten sam tekst, zaszyfrowany co poprzednio, tylko w innym języku :D 
To już byłoby chyba zbyt monotonne, a tak pozostaje lekkie uczucie niedosytu i moim zdaniem to świetnie :)
